'use client';
import { useEffect, useRef, useState } from 'react';
import gsap from 'gsap';
import { Marquee } from './ui/marquee';
import { GridPattern } from './ui/grid-pattern';
import { ProgressiveBlur } from './ui/progressive-blur';
import { InteractiveHoverButton } from './ui/interactive-hover-button';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
export function Stamp({date}:{date:string}){
 const [zoom,setZoom]=useState(false);const [point,setPoint]=useState({x:65,y:51});
 const visual=<><img src="/media/bag-label-macro.png" alt="One-way valve and roast-date label, in close detail"/><span className="live-stamp-date">{date || 'ROAST TO ORDER'}</span></>;
 return <section className="stamp section" data-component="composition1-stamp"><div className="section-kicker">01 / THE STAMP<span>READ THE SMALL PRINT.</span></div><div className="stamp-image" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setPoint({x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100})}}>{visual}<button className="lens-target" aria-label={zoom?'Close date magnifier':'Magnify the live roast date'} aria-pressed={zoom} onClick={()=>setZoom(!zoom)} onFocus={()=>setPoint({x:65,y:51})}>+</button>{zoom&&<div className="lens" style={{transformOrigin:`${point.x}% ${point.y}%`}}>{visual}</div>}</div><div className="stamp-copy"><p className="eyebrow">THE DATE IS PART OF THE PRODUCT.</p><h2>Roasted the day<br/>it shipped.<br/>Printed, not implied.</h2><p>No guesswork. The roast date belongs on the bag.</p></div><div className="leaders" aria-label="Label details"><span>VALVE ─────────</span><span>ROAST DATE ─────</span><span>BATCH ─────────</span></div></section>
}
export function LowerPage({checkoutUrl,date}:{checkoutUrl:string;date:string}){
 const scope=useRef<HTMLDivElement>(null);const comparison=useRef<HTMLSpanElement>(null);
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{
  const ctx=gsap.context(()=>{
   gsap.utils.toArray<HTMLElement>('[data-reveal]').forEach(el=>gsap.fromTo(el,{clipPath:'inset(0 0 100% 0)'},{clipPath:'inset(0 0 0% 0)',duration:.6,ease:'none',scrollTrigger:{trigger:el,start:'top 90%',toggleActions:'play none none reverse'}}));
   gsap.utils.toArray<HTMLElement>('.log-row').forEach((el,i)=>gsap.fromTo(el,{opacity:.2},{opacity:1,duration:.3,delay:i*.06,scrollTrigger:{trigger:'.roast-log',start:'top 75%'}}));
   const value={n:90};gsap.to(value,{n:180,ease:'none',scrollTrigger:{trigger:'.comparison',start:'top 65%',end:'center center',scrub:true},onUpdate:()=>{if(comparison.current)comparison.current.textContent=`90–${Math.round(value.n)}`}});
   
   ScrollTrigger.create({trigger:'.light-chapters',start:'top 55%',end:'bottom 45%',onToggle:s=>scope.current?.classList.toggle('light-active',s.isActive)});
  },scope);return()=>ctx.revert();});return()=>mm.revert()},[]);
 return <div ref={scope}>
  <section className="comparison section"><div className="section-kicker">02 / THE COMPARISON<span>ONE VARIABLE CHANGES EVERYTHING.</span></div><div className="comparison-grid"><div><span className="eyebrow">HOUR ZERO / OUT THE DOOR</span><p className="comparison-number">48<span>HOURS</span></p></div><div><span className="eyebrow">THE SHELF / TIME SINCE ROAST</span><p className="comparison-number"><span ref={comparison}>90–180</span><span>DAYS</span></p></div></div><h2 data-reveal>Most bags on a shelf were roasted three months ago. Ours left the drum yesterday.</h2></section>
  <div className="light-chapters"><section className="roast-log section" data-component="organism1-animated-list"><GridPattern width={80} height={80} className="log-grid"/><div className="section-kicker">03 / ROAST LOG<span>SMALL BATCH. ON THE RECORD.</span></div><h2 data-reveal>Every batch<br/>gets a timestamp.</h2><p className="data-note">BATCH RECORDS TO BE ANNOUNCED</p><div className="log-table" role="table" aria-label="Roast log awaiting batch records"><div className="log-header" role="row">{['DATE','ORIGIN','ROAST TIME','HOURS SINCE'].map(x=><span role="columnheader" key={x}>{x}</span>)}</div>{Array.from({length:8},(_,i)=><div className="log-row" role="row" key={i}>{['—','TO BE ANNOUNCED','—','—'].map((x,j)=><span role="cell" key={j}>{x}</span>)}</div>)}</div></section>
  <section className="origins section"><div className="section-kicker">04 / ORIGINS<span>TRACE IT BACK.</span></div><Marquee>ETHIOPIA / GUJI ─ NATURAL ─ HEIRLOOM ─ </Marquee><p className="data-note">ALTITUDE & ROAST LEVEL / TO BE ANNOUNCED</p></section></div>
  <section className="cafes section"><div className="section-kicker">05 / CAFES<span>THE SAME CLOCK, AT YOUR COUNTER.</span></div><Marquee reverse slow>WHOLESALE PARTNERS / TO BE ANNOUNCED ─ </Marquee></section>
  <section className="tasting section"><div className="section-kicker">06 / TASTING NOTES<span>START WITH THE CUP.</span></div><h2 data-reveal>The difference<br/>is in the time.</h2><p className="tasting-detail" data-reveal>Freshly roasted.<br/>Nothing left to guess.</p><p className="data-note">BATCH TASTING NOTES / TO BE ANNOUNCED</p></section>
  <section className="facts section"><div className="section-kicker">07 / FOUR FACTS<span>NO EXTRA INGREDIENTS.</span></div><div className="facts-grid">{[['Roast to order.','The order comes first. The roast follows.'],['48 hours.','From the roast to dispatch.'],['Connecticut.','Small-batch coffee. Made here.'],['Small batch.','Every roast gets our attention.']].map(([title,text],i)=><article data-reveal key={title} data-component={`molecule${i+2}-magic-card`}><span className="fact-index">{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="objections section"><ProgressiveBlur height="25px" blurLevels={[.5,1,2,3]}/><div className="section-kicker">08 / A FAIR QUESTION<span>YOU ALREADY HAVE A ROUTINE.</span></div><h2 data-reveal>Keep your ritual.<br/>Question the date.</h2>{[['I already buy coffee I like.','Start with the date on the bag. HOUR ZERO is roasted to order, with a roast date you can read. Let your next cup make the comparison.'],['When does it roast?','After you order. Small batches, roasted in Connecticut, then sealed the same day.'],['When does it ship?','Within 48 hours. Delivery details and the current offering will be available with ordering.']].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</section>
  <section id="buy" className="buy section"><img className="buy-image" src="/media/doorstep-48.png" alt="A plain shipping box on a doorstep"/><div className="section-kicker">09 / HOUR ZERO<span>THE CLOCK KEEPS GOING.</span></div><div className="buy-copy"><span className="buy-time">48h</span><h2>Buy a bag.</h2><p>Roasted to order.<br/>On your step in 48 hours.</p><InteractiveHoverButton href={checkoutUrl||'#ordering-status'}>BUY A BAG</InteractiveHoverButton>{!checkoutUrl&&<p id="ordering-status" className="ordering-status" tabIndex={-1}>ORDERING TO BE ANNOUNCED.</p>}</div><span className="buy-date">ROAST TO ORDER / {date}</span></section>
 </div>
}
